// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using spider.Data;

#nullable disable

namespace spider.Migrations
{
    [DbContext(typeof(SpiderDbContext))]
    [Migration("20220913095550_IniticalCreate_v2")]
    partial class IniticalCreate_v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("spider.Model.Product", b =>
                {
                    b.Property<string>("sku")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("abv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bottleSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("imagelink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("price")
                        .HasColumnType("real");

                    b.HasKey("sku");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
